work_type_mapper = {
    "journal-article": 1,
    "book-chapter": 2,
    "proceedings-article": 3,
    "dissertation": 4,
    "posted-content": 5,
    "book": 6,
    "dataset": 7,
    "journal-issue": 8,
    "report": 9,
    "other": 10,
    "reference-entry": 11,
    "monograph": 12,
    "reference-book": 13,
    "peer-review": 14,
    "component": 15,
    "standard": 16,
    "proceedings": 17,
    "journal": 18,
    "report-series": 19,
    "book-part": 20,
    "grant": 21,
    "journal-volume": 22,
    "book-series": 23,
    "proceedings-series": 24,
    "book-set": 25,
}

author_position_mapper = {"middle": 0, "first": 1, "last": 2}

journal_area_mapper = {
    "Agricultural and Biological Sciences": 1,
    "Arts and Humanities": 2,
    "Biochemistry": 3,
    "Business": 4,
    "Chemical Engineering": 5,
    "Chemistry": 6,
    "Computer Science": 7,
    "Decision Sciences": 8,
    "Dentistry": 9,
    "Earth and Planetary Sciences": 10,
    "Econometrics and Finance": 11,
    "Economics": 12,
    "Energy": 13,
    "Engineering": 14,
    "Environmental Science": 15,
    "Genetics and Molecular Biology": 16,
    "Health Professions": 17,
    "Immunology and Microbiology": 18,
    "Management and Accounting": 19,
    "Materials Science": 20,
    "Mathematics": 21,
    "Medicine": 22,
    "Multidisciplinary": 23,
    "Neuroscience": 24,
    "Nursing": 25,
    "Pharmacology": 26,
    "Physics and Astronomy": 27,
    "Psychology": 28,
    "Social Sciences": 29,
    "Toxicology and Pharmaceutics": 30,
    "Veterinary": 31,
}
